version: '3.1'

services:
    api:
        build: './api'
        environment:
            - PYTHONUNBUFFERED=1
            - FLASK_ENV=production
            - FLASK_APP=src/app.py
            - MIGRATE_ON=True
            - DEV_PG_URL=postgresql://admin:admin@db:5432/db
            - PRO_PG_URL=postgresql://p320_09:iem7iechae0phaM3ow4X@reddwarf.cs.rit.edu:5432/p320_09
        ports:
            - 5000:5000
        volumes: 
            - ./api/migrations:/migrations

    web:
        build: ./web
        tty: true
        environment:
            env_file: ./web/.env
            NODE_ENV: development
        volumes:
            - ./web:/app
            - /app/node_modules
        ports:
            - 3000:3000
        depends_on: 
            - api

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080